name: Trigger manual approval

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url without https://

jobs:
  manual_approve:
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.inputs.branch }}

      - name: Approve Backstop
        uses: ./.github/workflows/reusable-approval.yml
        with:
          deployed_url: ${{ github.ref_name }}
          branch: ${{ github.ref_name }}
