name: Create Snapshot

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: üõë Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v2

      - name: ‚éî Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: üì• Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Update to vercel deployed branch version
        run: |
          sed -i "s/http:\/\/localhost:3000/${{ github.event.inputs.vercel_deployed_url }}/g" backstop.json
          cat backstop.json
        shell: bash

      # as requested by the R
      - name: ‚¨ÜÔ∏è Run page rendering check
        continue-on-error: true
        run: npm run backstop:test

      - uses: actions/upload-artifact@v3
        with:
          name: backstop-artifact
          path: backstop_data/

      - name: Backstopjs snapshot is valid
        run: chmod a+x ./.github/scripts/snapshot-check.sh && ./.github/scripts/snapshot-check.sh
        shell: bash
